version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.3

    working_directory: /go/src/github.com/dnozdrin/piglatin
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
